export const getAbbreviation = (subject) => {
    if (!subject) return '';
    const map = {
        // common subjects with preferred short forms
        'ENGLISH': 'ENG',
        'HINDI': 'HIN',
        'FRENCH': 'FRE',
        'MALAYALAM': 'MAL',
        'SANSKRIT': 'SAN',
        'MATHEMATICS': 'MATH',
        'PHYSICS': 'PHY',
        'CHEMISTRY': 'CHEM',
        'BIOLOGY': 'BIO',
        'HISTORY': 'HIS',
        'GEOGRAPHY': 'GEO',
        'COMPUTER SCIENCE': 'CS',
        'COMPUTER APPLICATION': 'CA',
        'ACCOUNTANCY': 'ACC',
        'BUSINESS': 'BST',
        'BUSINESS STUDIES': 'BUS',
        'ECONOMICS': 'ECO',
        'ENTREPRENEURSHIP': 'ENT',
        'PSYCHOLOGY': 'PSY',
        'SOCIOLOGY': 'SOC',
        'SOCIAL STUDIES': 'SST',
        'SCIENCE': 'SCI',
        'PAINTING': 'PTG',
        'HOME SCIENCE': 'HSC',
        'ARTIFICIAL INTELLIGENCE': 'AI',
        'INTRODUCTION TO FINANCIAL MARKETS': 'IFM',
        'FOOD PRODUCTION': 'FP',
        'DATA SCIENCE': 'DS',
        'ENTREPRENEURSHIP': 'ENT',
        'INFORMATICS PRACTICES': 'IP',
        'LEGAL STUDIES': 'LEG',
        'APPLIED MATHEMATICS': 'APP M',
        'POLITICAL SCIENCE': 'POL SC',
        'PHYSICAL EDUCATION': 'PE',
        'SWIMMING': 'SWM',
        'MAJOR ARTS': 'MART',
        'MAJOR SPORTS': 'MSPT',
        'SKILL': 'SKL',
        'ART EDUCATION': 'ART',
        'MUSIC': 'MUS',
        'WORK EXPERIENCE': 'WE',
        'CLASS TEACHER TIME': 'CTT',
        'STEM': 'STEM'
    };
    return map[subject.toUpperCase()] || subject.substring(0, 3).toUpperCase();
};
